### ISSUE TITLE
macOS target

### ISSUE THREAD

**Issue by joreilly** [chrisbanes/material3-windowsizeclass-multiplatform#10]
Probably jumping the gun a bit here but any chance you could add a macOS target as well :)

**Comment by chrisbanes** [comment]
Mac (native ui-kit) isn't a supported target for Compose MP AFAIK?

**Comment by joreilly** [comment]
Ah, probably....I was doing quick try in existing KMP shared module that has macOS target but I probably should have a more UI specific shared module for something like this.

**Comment by joreilly** [comment]
works great!
https://github.com/chrisbanes/material3-windowsizeclass-multiplatform/assets/6302/65fa76aa-5d19-4afc-88a7-9ff5cd3a5604

**Comment by DatL4g** [comment]
@chrisbanes requesting to re-open this issue as macOs (native) is a supported Compose target

**Comment by chrisbanes** [comment]
> @chrisbanes requesting to re-open this issue as macOs (native) is a supported Compose target

Got a link confirming this?

JVM 'Desktop' is a CMP target, which is already supported by this library.

**Comment by DatL4g** [comment]
@chrisbanes here you go:

https://mvnrepository.com/artifact/org.jetbrains.compose.ui/ui-macosx64
https://mvnrepository.com/artifact/org.jetbrains.compose.ui/ui-macosarm64

**Comment by chrisbanes** [comment]
> @chrisbanes here you go:
> 
> https://mvnrepository.com/artifact/org.jetbrains.compose.ui/ui-macosx64 https://mvnrepository.com/artifact/org.jetbrains.compose.ui/ui-macosarm64

That does not mean that there is native support. The [Compose Multiplatform landing page](https://www.jetbrains.com/lp/compose-multiplatform/) clearly lists out the supported platforms, and MacOS (native) isn't there.

**Comment by DatL4g** [comment]
Sorry but you're surprised that a single target isn't listed on a beginner-friendly introduction page, which additionally has roughly 15% market share while the bigger desktop target is only support through JVM?

**That's hilarious.**

All required packages are published for macOs, if they would not support the target, they would not be available as there isn't any package for linux or mingw for example. (Except runtime)

Runtime: https://mvnrepository.com/artifact/org.jetbrains.compose.runtime/runtime-macosx64
Foundation: https://mvnrepository.com/artifact/org.jetbrains.compose.foundation/foundation-macosx64
UI: https://mvnrepository.com/artifact/org.jetbrains.compose.ui/ui-macosx64
Material: https://mvnrepository.com/artifact/org.jetbrains.compose.material/material-macosx64
Material3: https://mvnrepository.com/artifact/org.jetbrains.compose.material3/material3-macosx64
Animation: https://mvnrepository.com/artifact/org.jetbrains.compose.animation/animation-macosx64
(New) Resources: https://mvnrepository.com/artifact/org.jetbrains.compose.components/components-resources-macosX64

**Comment by chrisbanes** [comment]
PRs welcome.
