### ISSUE TITLE
Library is now deprecated

### ISSUE THREAD

**Issue by chrisbanes** [chrisbanes/material3-windowsizeclass-multiplatform#100]
This is a future notice that this library will _soon_ be deprecated. 

The window size class library is now included in Compose Multiplatform 1.7.0 (currently pre-release). This library will be deprecated as soon as 1.7.0 goes stable.

**Comment by harish-zuper** [comment]
Thanks for the info :)

**Comment by chrisbanes** [comment]
Yep, just updated this issue’s description.

**Comment by CXwudi** [comment]
Hi, today 1.7.0 goes GA. However, based on the [release note](https://www.jetbrains.com/help/kotlin-multiplatform-dev/whats-new-compose-170.html#material3-material3-window-size-class), it lacks a commonized `calculateWindowSizeClass()` method, which I believe is still necessary for adaptive UI. There are two options:

1. Adapt this library to depends on the new `material3-window-size-class` and simply provide a commonized `calculateWindowSizeClass()` method
2. Still deprecate this library but extract the [commonized `calculateWindowSizeClass()` implementation](https://github.com/search?q=repo%3Achrisbanes%2Fmaterial3-windowsizeclass-multiplatform%20calculateWindowSizeClass&type=code) into a GitHub Gist for future reference, or create a new library just for commonized `calculateWindowSizeClass()`

I am fine with either options

**Comment by chrisbanes** [comment]
Thanks for the update. 

I have no plans to make any further changes to this library, so will proceed with the deprecation as planned.

As to comminization, I think that this is best handled at the app level. AFAICT, the JetBrains team hasn’t added a common function yet, because they haven’t implemented the necessary hooks on certain platforms. All of the major platforms have a `calculateWindowSizeClass()` function though, so it's just a case of adding some trivial expect/actual functions.

**Comment by skaldebane** [comment]
I guess it might be a good idea to archive the repository as well.
