### ISSUE TITLE
crash on mac m1rpo

### ISSUE THREAD

**Issue by HuixingWong** [chrisbanes/material3-windowsizeclass-multiplatform#17]
When i add this dependencies on my project then run on desktop crashed with this error 

 .UnsatisfiedLinkError: 'long org.jetbrains.skiko.context.MetalContextHandler.makeMetalContext(long)

**Comment by chrisbanes** [comment]
That obviously isn't enough information. A quick Google search brought up this: https://github.com/JetBrains/compose-multiplatform/issues/3282.

I recommend checking what version of Compose Multiplatform you are using.
