### ISSUE TITLE
Use LTS Java Runtime for Releases

### ISSUE THREAD

**Issue by DATL4G** [chrisbanes/material3-windowsizeclass-multiplatform#28]
Please use Long-Term-Support versions of the Java Runtime to compile releases.
The current release (`0.3.0`) uses Java version 19, so applications have to rely on at least that version or higher, however there is currently no newer LTS release, which may break stuff in some development environments

[endoflife.date/java](https://endoflife.date/java)

**Comment by chrisbanes** [comment]
Not sure what happened here. Re-released, built with JDK 17: https://github.com/chrisbanes/material3-windowsizeclass-multiplatform/releases/tag/v0.3.1
