### ISSUE TITLE
Can't Import Library using Kotlin/Wasm Alpha 

### ISSUE THREAD

**Issue by luludevmuniz** [chrisbanes/material3-windowsizeclass-multiplatform#57]
As [Kotlin for WebAssembly gone from Experimental to Alpha](https://blog.jetbrains.com/kotlin/2023/12/kotlin-for-webassembly-goes-alpha/), it became a target option when creating a new project template in [https://kmp.jetbrains.com/](https://kmp.jetbrains.com/)

However, when I add the material3-windowsizeclass-multiplatform dependency, the gradle won't sync.

`
No matching variant of dev.chrisbanes.material3:material3-window-size-class-multiplatform:0.3.1 was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm', attribute 'or
g.jetbrains.kotlin.wasm.target' with value 'js' but...
`

[FullGradleSyncError.txt](https://github.com/chrisbanes/material3-windowsizeclass-multiplatform/files/13606301/GradleSyncError.txt)
[composeAppBuildGradle.txt](https://github.com/chrisbanes/material3-windowsizeclass-multiplatform/files/13606333/composeAppBuildGradle.txt)

**Comment by luludevmuniz** [comment]
Ok, I figured out that the must go in the commonMain dependencies inside the **shared** module, not the **composeApp**.

**Comment by luludevmuniz** [comment]
False positive, **I can** import it from shared module, but **can't** use in the Web target.

**Comment by chrisbanes** [comment]
Yeah, we'll likely need to produce a build against Compose Multiplatform [1.6.0-alpha01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-alpha01). I can't just do that in the main branch though as I want to keep that 'stable'.

I've started migrating in #58 but I won't have time to look again until next week.

**Comment by chrisbanes** [comment]
Released in [0.5.0-alpha01](https://github.com/chrisbanes/material3-windowsizeclass-multiplatform/releases/tag/0.5.0-alpha01). I haven't performed extensive testing, but the sample works nicely.
