### ISSUE TITLE
Support Web platform

### ISSUE THREAD

**Issue by chrisbanes** [chrisbanes/material3-windowsizeclass-multiplatform#8]

**Comment by JamshedAlamQaderi** [comment]
When a release will be made for this update

**Comment by alexstyl** [comment]
second that. I'm also looking forward to the release

**Comment by chrisbanes** [comment]
Sorry about the delay. I wanted to test the web build a bit more before releasing, but life happened and I forgot. Anyway, I'm on it today so will hopefully have something out today/tomorrow.

**Comment by JamshedAlamQaderi** [comment]
Thank you so much. I needed this update...
