### ISSUE TITLE
WindowSizeClass is always Expanded in web

### ISSUE THREAD

**Issue by Not-Soti** [chrisbanes/material3-windowsizeclass-multiplatform#88]
**Problem:**
Using compose multiplatform to build a web, the calculateWindowSizeClass() will always return that both Width and Height size classes are Expanded regardless of the device.

**Description:**
I'm using the KMM and Compose to build a WASM web, and tested it using 2 computer screens and an android mobile phone to access it. In the phone, the method is still returning that both widthSizeClass and heightSizeClass are Exanded when at least the width should be Compact.

**Comment by chrisbanes** [comment]
I've just tried the WASM sample app on my laptop (using Firefox and Chrome) and the returned size classes are as expected.

I can take a further look if you can provide a reproducible example.

**Comment by Not-Soti** [comment]
Hi @chrisbanes, thank you for your time.

I've just cloned this repo and launched the wasm sample app using the "wasmJsBrowserRun" gradle task. After opening the web in my phone with Chrome and in the native browser  it still says that both the width and height classes are Expanded

**Comment by chrisbanes** [comment]
Just tried this on an Android emulator, and yes confirmed. 

The issue isn't really anything to do with this library though, more how you're setting up the host webpage. Viewport sizes in CSS and HTML are complex, and I've just realised that the samples are missing a `meta` tag to make it work more correctly. You can see an example in 0a052aea.
